### ISSUE TITLE
fast-deep-equal-over-microdiff: autofix emits 'fast-deep-equal', but agora depends on @blumintinc/fast-deep-equal

### ISSUE THREAD

**Issue by oconnorjoseph** [BluMintInc/eslint-custom-rules#1533]
## Summary

`fast-deep-equal-over-microdiff`'s autofix emits `import isEqual from 'fast-deep-equal';` — a package agora does not depend on. agora depends on **`@blumintinc/fast-deep-equal`** (`"4.0.0"`). This is the same defect class as #1531, latent only because agora currently has zero violations of this rule.

## Verified against agora

Dependency: `"@blumintinc/fast-deep-equal": "4.0.0"` — there is no unscoped `fast-deep-equal` dependency.

Import sites:

| specifier | sites |
|---|---|
| `@blumintinc/fast-deep-equal` | 44 |
| `@blumintinc/fast-deep-equal/react` | 17 |
| `fast-deep-equal` | 1 (undeclared — an agora-side bug, not this rule's) |

So the **base scoped package is the dominant convention**, 44 to 17. That resolves the base-vs-`/react` question: emit `@blumintinc/fast-deep-equal`.

Type-checking the fixer's output against agora's actual dependency set (unscoped `fast-deep-equal` absent) gives `TS2307: Cannot find module 'fast-deep-equal' or its corresponding type declarations` on every fixed file.

## Second consequence

The rule's recognition set is `{'fast-deep-equal', 'fast-deep-equal/es6'}`. A file already importing `isEqual` from `@blumintinc/fast-deep-equal` is not recognised as satisfying the rule, so it hits the existing-binding guard and gets a report with **no fix at all** — an unactionable report, which in this org blocks adoption outright.

## Suggested fix

- Emit `@blumintinc/fast-deep-equal`.
- Recognise all four specifiers when reading existing imports: `fast-deep-equal`, `fast-deep-equal/es6`, `@blumintinc/fast-deep-equal`, `@blumintinc/fast-deep-equal/react`.
- `DEFAULT_IGNORED_LIBRARIES` in `src/rules/enforce-dynamic-imports.ts` lists only the unscoped `fast-deep-equal`; the scoped name must be added or `recommended-config-fix-closure` will fail on the newly emitted import. That is a second rule file, so it needs its own one-rule commit — do NOT fold it in; report it and it will be sequenced.
- Expect ~45 expected outputs plus the docs to change.

## Related cleanup (separate commits, do not fold in)

`src/utils/microdiffModules.ts` was introduced in #1532 as the shared home for microdiff specifiers, but `src/rules/enforce-microdiff.ts` and `src/rules/enforce-dynamic-imports.ts` still carry their own literals. The microdiff pair has now drifted twice (#1531, #1532); a `fastDeepEqualModules` constant in the same shape would prevent a third.
