### ISSUE TITLE
enforce-timestamp-now: autofix breaks every Date method the Timestamp shape lacks (TS2339) — the exclusion list is an incomplete denylist

### ISSUE THREAD

**Issue by oconnorjoseph** [BluMintInc/eslint-custom-rules#1528]
## Summary

`enforce-timestamp-now` rewrites `const now = new Date()` to `Timestamp.now()` without checking what the resulting value is *used for*. `Timestamp` has none of `Date`'s formatting/accessor methods, so every subsequent call on that variable becomes `TS2339`.

## Root cause

`isDateBeingModified` (`src/rules/enforce-timestamp-now.ts`) is documented as "Check if a Date object is being modified (e.g. `futureDate.setDate()`)", but what it actually functions as is an **incomplete denylist of Date members `Timestamp` does not have**:

```ts
parent.property.name.startsWith('set') ||
parent.property.name === 'toISOString' ||
parent.property.name === 'toLocaleString' ||
parent.property.name === 'toString'
```

`toISOString` / `toLocaleString` / `toString` are not modifications — they are there because `Timestamp` lacks them. The list omits every other `Date`-only member.

## Verified reproduction

With a real `Timestamp` shape (`static now()`, `toDate()`, `toMillis()`), in a backend path, with the import present so the #1521 gate passes:

```ts
import { Timestamp } from 'firebase-admin/firestore';
export function f() {
  const now = new Date();
  return now.toLocaleDateString();
}
```

`eslint --fix` yields `const now = Timestamp.now();` and then:

```
TS2339: Property 'toLocaleDateString' does not exist on type 'Timestamp'.
```

tsc before: **clean**; after: **TS2339**. Measured across members — fixed and broken: `toLocaleDateString`, `toLocaleTimeString`, `getTime`, `getFullYear`, `toDateString`. Correctly skipped: `toISOString`. Fixed and harmless: `valueOf` (inherited from Object).

This is pre-existing, not introduced by #1521: the old inert guard also fixed these, and with an import present it produced the same TS2339.

## Suggested fix

Invert the check. Instead of denying a hand-picked set of `Date` members, only offer the fix when every member access on the bound variable is one `Timestamp` actually supports (`toDate`, `toMillis`, `isEqual`, `seconds`, `nanoseconds`, `valueOf`). Anything else — including an unknown member, a pass to a function, or a use as a value — should decline. Prefer false negatives over emitting broken code.

Rename `isDateBeingModified` to say what it checks; the current name is what allowed the list to be extended incorrectly.

## Why the guard missed it

`src/tests/fixer-type-safety.test.ts` stubs modules with `declare module '*'`, which types every imported binding as `any`, so `Timestamp.now().toLocaleDateString()` type-checks in the harness. Filed separately as the guard's blind spot.
